// Generated by CoffeeScript 2.5.1
(function() {
  var utils, yeoman;

  yeoman = require('yeoman-generator');

  utils = require('../utils');

  module.exports = yeoman.generators.Base.extend({
    checkForConfig: function() {
      var cb;
      cb = this.async();
      if (!(this.filters = this.config.get('filters'))) {
        this.log('Cannot find the config file');
        return;
      }
      return cb();
    },
    write: function() {
      return utils.write(this, this.filters);
    }
  });

}).call(this);
